# Generated by Django 4.2.3 on 2023-07-11 13:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_education_alter_experience_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='departmant',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Departmant'),
        ),
        migrations.AddField(
            model_name='education',
            name='score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='Score'),
        ),
    ]
