# Generated by Django 4.2.3 on 2023-07-11 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_education_departmant_education_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='Score'),
        ),
    ]
