# Generated by Django 4.2.3 on 2023-07-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_education_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='file',
            field=models.ImageField(blank=True, default='', upload_to='images/', verbose_name='Image'),
        ),
    ]
