# Generated by Django 4.2.3 on 2023-08-02 07:40

from django.db import migrations, models
import resume.custom_storage


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_document_file_alter_document_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, default='', storage=resume.custom_storage.DocumentStorage(), upload_to='', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='imagesetting',
            name='file',
            field=models.ImageField(blank=True, default='', upload_to=resume.custom_storage.ImageSettingsStorage(), verbose_name='Image'),
        ),
    ]
